### ISSUE TITLE
example not working with both sample data and downloaded data

### ISSUE THREAD

**Issue by WenchenLi** [SimFin/bd-extractor#4]
`./processSimfin.py --inputFile=sample-data.csv --minYear=2016 --tickers=AAPL,MSFT`
result is empty

**Comment by thf24** [comment]
Hi,

processSimfin.py is community contributed and not tested with the current version - I will check it later again.

extractor.py should work as intended if you run sample-extraction.py

**Comment by thf24** [comment]
Just checked again, it is running fine for me. What python version are you using?
